//completed

package p02;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class P2 {

	public static void main (String[] args) {
		int a = 1;
		int b = 2;
		int limit = 4000000;
		int count = 0;
		while (b <= limit) {
			if(b % 2 == 0) {
				count += b;
			}
			int c = b;
			b = a + b;
			a = c;
		}
		
		System.out.println(count);
	}
}
